version: "3.8"

services:
  db:
    image: postgres:15.4
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-task-tracker
    environment:
      API_PORT: 8080
      DB_CONNECTION_URL: "postgres://postgres:password@db:5432/postgres?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
