// Code generated by MockGen. DO NOT EDIT.
// Source: ./uc/tasks.go

// Package mock is a generated GoMock package.
package mock

import (
	domain "api/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTasksUC is a mock of TasksUC interface.
type MockTasksUC struct {
	ctrl     *gomock.Controller
	recorder *MockTasksUCMockRecorder
}

// MockTasksUCMockRecorder is the mock recorder for MockTasksUC.
type MockTasksUCMockRecorder struct {
	mock *MockTasksUC
}

// NewMockTasksUC creates a new mock instance.
func NewMockTasksUC(ctrl *gomock.Controller) *MockTasksUC {
	mock := &MockTasksUC{ctrl: ctrl}
	mock.recorder = &MockTasksUCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksUC) EXPECT() *MockTasksUCMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTasksUC) CreateTask(ctx context.Context, data domain.Task) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, data)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTasksUCMockRecorder) CreateTask(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTasksUC)(nil).CreateTask), ctx, data)
}

// GetTaskById mocks base method.
func (m *MockTasksUC) GetTaskById(ctx context.Context, id uuid.UUID) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskById", ctx, id)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskById indicates an expected call of GetTaskById.
func (mr *MockTasksUCMockRecorder) GetTaskById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskById", reflect.TypeOf((*MockTasksUC)(nil).GetTaskById), ctx, id)
}

// GetTasks mocks base method.
func (m *MockTasksUC) GetTasks(ctx context.Context) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockTasksUCMockRecorder) GetTasks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockTasksUC)(nil).GetTasks), ctx)
}
