name: Go CD (Release Build)

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download Go dependencies
        run: go mod download

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint code with staticcheck
        run: $(go env GOPATH)/bin/staticcheck ./...

      - name: Run tests
        run: go test ./...

      - name: Build binary
        run: go build -o myapp

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: myapp
